apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tanzu-java-web-app
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    app.kubernetes.io/part-of: tanzu-java-web-app
    carto.run/workload-name: tanzu-java-web
    carto.run/workload-namespace: dev
spec:
  build:
    env:
    - name: BP_EMBED_CERTS
      value: "true"
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  - name: buildServiceBindings
    value:
    - kind: Secret
      name: supportlabsrootca
  source:
    git:
      url: https://github.com/David-VMware/Tanzu-Java-Web-App
      ref:
        branch: ca-cert
